import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/ui/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ts - Cruds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-black`}>
        <AuthProvider>
          <Header />
          <main className="min-h-[calc(100vh-128px)]">{children}</main>
          <footer className="border-t bg-white">
            <div className="max-w-6xl mx-auto px-4 py-6 text-sm text-gray-600">
              <span className="font-semibold text-gray-900">Technova</span> · © {new Date().getFullYear()}
            </div>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
